version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000' # API порт
      - '9001:9001' # Web UI порт
    environment:
      MINIO_ROOT_USER: minioadmin # Логин
      MINIO_ROOT_PASSWORD: minioadmin # Пароль
      MINIO_REGION: us-east-1 # Настройка региона
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data # Локальная папка для хранения данных MinIO

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432' # PostgreSQL порт
    environment:
      POSTGRES_USER: postgres # Логин
      POSTGRES_PASSWORD: admin # Пароль
      POSTGRES_DB: filmlingo # Имя базы данных
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Локальная папка для хранения данных PostgreSQL
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d filmlingo -U postgres" ]
      interval: 7s
      timeout: 15s
      retries: 3
      start_period: 25s

  mailer:
    image: mailhog/mailhog:latest
    container_name: filmlingo-mailer
    ports:
      - "1025:1025" # SMTP порт
      - "8025:8025" # Веб-интерфейс для просмотра писем

#  telegram-bot:
#    build: ../filmlingo-bot
#    container_name: filmlingo-telegram-bot
#    restart: always
#    env_file:
#      - ../filmlingo-bot/.env
#    depends_on:
#      - postgres
#      - minio

#  backend:
#    build: ./
#    restart: always
#    ports:
#      - "8000:8000"
#    env_file:
#      - ./.production.env
#    container_name: filmlingo_be_test_cont
#    depends_on:
#      postgres:
#          condition: service_started
#      mailer:
#        condition: service_started
#      minio:
#        condition: service_started
#
#  frontend:
#    build:
#      context: ../filmlingo-fe
#      args:
#        NEXT_PUBLIC_API_URL: http://localhost:8000
#        NEXT_PUBLIC_STATIC: http://localhost:9000/filmlingo
#    restart: always
#    ports:
#      - "3000:3000"
#    container_name: filmlingo_fe_test_cont

volumes:
  minio-data: # Том для MinIO (если не хотите использовать локальную папку)
  postgres-data: # Том для PostgreSQL (если не хотите использовать локальную папку)
